export const GET_UNITS_REQUEST = 'IR/UNITS/GET/REQUEST'
export const GET_UNITS_SUCCESS = 'IR/UNITS/GET/SUCCESS'
export const GET_UNITS_ERROR = 'IR/UNITS/GET/ERROR'

export const ADD_UNIT_REQUEST = 'IR/UNIT/ADD/REQUEST'
export const ADD_UNIT_SUCCESS = 'IR/UNIT/ADD/SUCCESS'
export const ADD_UNIT_ERROR = 'IR/UNIT/ADD/ERROR'

export const UPDATE_UNIT_REQUEST = 'IR/UNIT/UPDATE/REQUEST'
export const UPDATE_UNIT_SUCCESS = 'IR/UNIT/UPDATE/SUCCESS'
export const UPDATE_UNIT_ERROR = 'IR/UNIT/UPDATE/ERROR'

export const DELETE_UNIT_REQUEST = 'IR/UNIT/DELETE/REQUEST'
export const DELETE_UNIT_SUCCESS = 'IR/UNIT/DELETE/SUCCESS'
export const DELETE_UNIT_ERROR = 'IR/UNIT/DELETE/ERROR'
