export const LOGIN_REQUEST = 'IR/USER/LOGIN/REQUEST'
export const LOGIN_SUCCESS = 'IR/USER/LOGIN/SUCCESS'
export const LOGIN_ERROR = 'IR/USER/LOGIN/ERROR'

export const LOGOUT_REQUEST = 'IR/USER/LOGOUT/REQUEST'
export const LOGOUT_SUCCESS = 'IR/USER/LOGOUT/SUCCESS'
export const LOGOUT_ERROR = 'IR/USER/LOGOUT/ERROR'
